force-app/main/default/objects/Case/fields/Academic_Performance_Reason_s__c.field-meta.xml
<CustomField>
    <fullName>Academic_Performance_Reason_s__c</fullName>
    <label>Academic Performance Reason(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Performance on tests</fullName>
            </value>
            <value>
                <fullName>Performance on assignments or papers</fullName>
            </value>
            <value>
                <fullName>Missing assignments</fullName>
            </value>
            <value>
                <fullName>Missing tests or other major assessments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Alert_Term_lookup__c.field-meta.xml
<CustomField>
    <fullName>Alert_Term_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the term object for this alert. Use the Banner term format (example: 202040) and not the friendly name format (example Fall 2020)</description>
    <inlineHelpText>Lookup to the term object for this alert. Use the Banner term format (example: 202040) and not the friendly name format (example Fall 2020)</inlineHelpText>
    <label>Alert Term (lookup)</label>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Alert Term Cases</relationshipLabel>
    <relationshipName>Alert_Term_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Attendance_Concerns_Reason_s__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Concerns_Reason_s__c</fullName>
    <label>Attendance Concerns Reason(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Missing periodically</fullName>
            </value>
            <value>
                <fullName>Missing excessively</fullName>
            </value>
            <value>
                <fullName>Stopped attending and/or never attended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Reporter__c.field-meta.xml
<CustomField>
    <fullName>Case_Reporter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Faculty or Staff member who opened this case.</description>
    <label>Case Reporter</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Case Reporter)</relationshipLabel>
    <relationshipName>Tommie_Cares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Course_Connection__c.field-meta.xml
<CustomField>
    <fullName>Course_Connection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Connection</label>
    <referenceTo>hed__Course_Enrollment__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>Course_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Offering</label>
    <referenceTo>hed__Course_Offering__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Faculty_Advisor__c.field-meta.xml
<CustomField>
    <fullName>Faculty_Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Faculty Advisor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Faculty Advisor)</relationshipLabel>
    <relationshipName>Cases8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Faculty_Advisor_Email__c.field-meta.xml
<CustomField>
    <fullName>Faculty_Advisor_Email__c</fullName>
    <label>Faculty Advisor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Financial_Aid_Counselor__c.field-meta.xml
<CustomField>
    <fullName>Financial_Aid_Counselor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Aid Counselor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Financial Aid Counselor)</relationshipLabel>
    <relationshipName>Cases4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Financial_Aid_Counselor_Email__c.field-meta.xml
<CustomField>
    <fullName>Financial_Aid_Counselor_Email__c</fullName>
    <label>Financial Aid Counselor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/First_Year_Advisor__c.field-meta.xml
<CustomField>
    <fullName>First_Year_Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>First-Year Advisor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (First-Year Advisor)</relationshipLabel>
    <relationshipName>Cases3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/First_Year_Advisor_Email__c.field-meta.xml
<CustomField>
    <fullName>First_Year_Advisor_Email__c</fullName>
    <label>First-Year Advisor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/General_Advisor__c.field-meta.xml
<CustomField>
    <fullName>General_Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>General Advisor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (General Advisor)</relationshipLabel>
    <relationshipName>Cases9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/General_Advisor_Email__c.field-meta.xml
<CustomField>
    <fullName>General_Advisor_Email__c</fullName>
    <label>General Advisor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/International_Advisor__c.field-meta.xml
<CustomField>
    <fullName>International_Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>International Advisor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (International Advisor)</relationshipLabel>
    <relationshipName>Cases6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/International_Advisor_Email__c.field-meta.xml
<CustomField>
    <fullName>International_Advisor_Email__c</fullName>
    <label>International Advisor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Primary_Advisor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Advisor_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Advisor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Primary Advisor Contact)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Primary_Advisory_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Advisory_Email__c</fullName>
    <label>Primary Advisory Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Probation_Advisor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Probation_Advisor_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Probation Advisor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Probation Advisor Contact)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Probation_Advisor_Email__c.field-meta.xml
<CustomField>
    <fullName>Probation_Advisor_Email__c</fullName>
    <label>Probation Advisor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Reporter_University_Email__c.field-meta.xml
<CustomField>
    <fullName>Reporter_University_Email__c</fullName>
    <label>Reporter University Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Student_Athlete_Advisor__c.field-meta.xml
<CustomField>
    <fullName>Student_Athlete_Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student-Athlete Advisor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Student-Athlete Advisor)</relationshipLabel>
    <relationshipName>Cases5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Student_Athlete_Advisor_Email__c.field-meta.xml
<CustomField>
    <fullName>Student_Athlete_Advisor_Email__c</fullName>
    <label>Student-Athlete Advisor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tommie_Alert_Primary_Reason__c.field-meta.xml
<CustomField>
    <fullName>Tommie_Alert_Primary_Reason__c</fullName>
    <inlineHelpText>Behavior concerns (threatening, intimidating, disrespectful, hostile, etc)
Mental health concerns (anxiety, depression, mood swings, etc)
Sense of belonging (not connecting on campus)</inlineHelpText>
    <label>Tommie Alert Reason(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tommie High 5</fullName>
            </value>
            <value>
                <fullName>Attendance concerns</fullName>
            </value>
            <value>
                <fullName>Academic performance concerns</fullName>
            </value>
            <value>
                <fullName>Behavior concerns</fullName>
            </value>
            <value>
                <fullName>Financial concerns</fullName>
            </value>
            <value>
                <fullName>Mental health concerns</fullName>
            </value>
            <value>
                <fullName>Relationship violence/stalking</fullName>
            </value>
            <value>
                <fullName>Sense of belonging</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Non-Responsive to Outreach</fullName>
            </value>
            <value>
                <fullName>Missed Advising Appointment</fullName>
            </value>
            <value>
                <fullName>Difficulty Meeting Basic Needs (food/housing, etc)</fullName>
            </value>
            <value>
                <fullName>Life Circumstances Impacting Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Tommie_High_5__c.field-meta.xml
<CustomField>
    <fullName>Tommie_High_5__c</fullName>
    <description>Keep Up the Good Work (use to recognize good work in the classroom) 
Showing Improvement (use when a student has showed improvement in a course</description>
    <inlineHelpText>Keep Up the Good Work (use to recognize good work in the classroom) 
Showing Improvement (use when a student has showed improvement in a course</inlineHelpText>
    <label>Tommie High 5 Reason(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Keep Up the Good Work</fullName>
            </value>
            <value>
                <fullName>Showing Improvement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CanvasTommieAlertsController.cls
/**
 * Created by Thaddaeus Dahlberg, Software Engineer, University of St. Thomas on 6/4/2024.
 */


public with sharing class CanvasTommieAlertsController {
    public String bannerId { get; set; }
    public Contact advisor { get; set; }
    public hed__Term__c currentTerm { get; set; }
    public List<SelectOption> courses { get; set; }
    public Case tommieCaresCase { get; set; }
    public Id studentCourseConnection { get; set; }
    public Id studentCourseEnrollment { get; set; }
    public Id courseOfferingId { get; set; }
    public String primaryConcern { get; set; }
    public String highFiveReason { get; set; }
    public String academicConcern { get; set; }
    public String attendanceConcern { get; set; }
    public doCrud crud2Do { get; set; }
    public Boolean caseSubmitted { get; set; }

    public CanvasTommieAlertsController() {

        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:Canvas_Tommie_Alert_NC');
        req.setMethod('GET');
        Http http = new Http();
        HTTPResponse res = http.send(req);
        System.debug(res.getBody());

        tommieCaresCase = new Case();
        caseSubmitted = false;
        crud2Do = new doCrud();
        if (String.isNotBlank(ApexPages.currentPage().getParameters().get('bid'))) {
            bannerId = ApexPages.currentPage().getParameters().get('bid').escapeHtml4();
        }

        if (String.isNotBlank(ApexPages.currentPage().getParameters().get('submitted'))) {
            try {
                caseSubmitted = Boolean.valueOf(ApexPages.currentPage().getParameters().get('submitted').escapeHtml4());
            } catch (Exception e) {

            }
        }

        currentTerm = [
                SELECT Id
                FROM hed__Term__c
                WHERE Current_Term__c = TRUE
                LIMIT 1
        ];

        if (String.isNotBlank(bannerId)) {
            advisor = crud2Do.getAdvisor(bannerId);
            if (advisor != null) {
                courses = crud2Do.getCourses(bannerId);
                System.debug(courses);
            }
        }
    }

    public List<SelectOption> getStudentsOptions() {
        return crud2Do.getStudents(studentCourseConnection);
    }

    public List<SelectOption> getPrimaryReasonOptions() {
        return getPicklists(Case.Tommie_Alert_Primary_Reason__c.getDescribe(), false);
    }

    public List<SelectOption> getAcademicConcernOptions() {
        return getPicklists(Case.Academic_Performance_Reason_s__c.getDescribe(), false);
    }

    public List<SelectOption> getAttendanceConcernsOptions() {
        return getPicklists(Case.Attendance_Concerns_Reason_s__c.getDescribe(), false);
    }

    public List<SelectOption> getTommieHigh5ReasonOptions() {
        return getPicklists(Case.Tommie_High_5__c.getDescribe(), false);
    }

    public PageReference saveCase() {
        Id tcCaseRTID = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Tommie Cares').getRecordTypeId();

        PageReference savePage = Page.TommieCares;
        if (String.isNotBlank(bannerId)) {
            savePage.getParameters().put('bid', bannerId);
            savePage.getParameters().put('submitted', 'true');
            savePage.setRedirect(true);
        }
        tommieCaresCase.RecordTypeId = tcCaseRTID;
        tommieCaresCase.Case_Reporter__c = advisor.Id;
        tommieCaresCase.Subject = 'Tommie Cares';
        tommieCaresCase.Origin = 'Web';
        tommieCaresCase.Reporter_University_Email__c = advisor.hed__UniversityEmail__c;

        tommieCaresCase.Course_Offering__c = studentCourseConnection;
        tommieCaresCase.Alert_Term_lookup__c = currentTerm.Id;
        tommieCaresCase.Tommie_Alert_Primary_Reason__c = primaryConcern;
        tommieCaresCase.Tommie_High_5__c = highFiveReason;
        tommieCaresCase.Attendance_Concerns_Reason_s__c = attendanceConcern;
        tommieCaresCase.Academic_Performance_Reason_s__c = academicConcern;

        //Get Course Connection for student selected
        List<hed__Course_Enrollment__c> studentCourseEnrollmentList = [
                SELECT Id
                FROM hed__Course_Enrollment__c
                WHERE Course_Offering_ID__c = :tommieCaresCase.Course_Offering__c
                AND hed__Contact__c = :tommieCaresCase.ContactId
        ];

        if (studentCourseEnrollmentList.size() > 0) {
            tommieCaresCase.Course_Connection__c = studentCourseEnrollmentList[studentCourseEnrollmentList.size() - 1].Id;
        }

        List <String> relationshipTypes = new List<String>{
                'Primary Advisor',
                'Student-Athlete Advisor',
                'Secondary Advisor',
                'First-Year Advisor',
                'Probationary Advisor',
                'Financial Aid Counselor',
                'General Advisor',
                'International Advisor',
                'Faculty Advisor'
        };

        List<hed__Relationship__c> advisorContacts = [
                SELECT hed__Contact__c, hed__Contact__r.Name, Name, hed__Type__c, hed__RelatedContact__r.Name, hed__Contact__r.Email
                FROM hed__Relationship__c
                WHERE hed__Type__c IN :relationshipTypes
                AND hed__RelatedContact__c = :tommieCaresCase.ContactId
                ORDER BY CreatedDate DESC NULLS LAST
        ];

        Map<String, hed__Relationship__c> advisorContactsMap = new Map<String, hed__Relationship__c>();
        for (hed__Relationship__c contact : advisorContacts) {
            advisorContactsMap.put(contact.hed__Type__c, contact);
        }

        if (advisorContactsMap.size() > 0) {
            tommieCaresCase.Primary_Advisor_Contact__c = getAdvisorInfo('Id', 'Primary Advisor', advisorContactsMap);
            tommieCaresCase.Primary_Advisory_Email__c = getAdvisorInfo('Email', 'Primary Advisor', advisorContactsMap);
            tommieCaresCase.Student_Athlete_Advisor_Email__c = getAdvisorInfo('Email', 'Student-Athlete Advisor', advisorContactsMap);
            tommieCaresCase.Student_Athlete_Advisor__c = getAdvisorInfo('Id', 'Student-Athlete Advisor', advisorContactsMap);
            tommieCaresCase.Secondary_Advisor_Email__c = getAdvisorInfo('Email', 'Secondary Advisor', advisorContactsMap);
            tommieCaresCase.Secondary_Advisor__c = getAdvisorInfo('Id', 'Secondary Advisor', advisorContactsMap);
            tommieCaresCase.First_Year_Advisor_Email__c = getAdvisorInfo('Email', 'First-Year Advisor', advisorContactsMap);
            tommieCaresCase.First_Year_Advisor__c = getAdvisorInfo('Id', 'First-Year Advisor', advisorContactsMap);
            tommieCaresCase.Probation_Advisor_Email__c = getAdvisorInfo('Email', 'Probationary Advisor', advisorContactsMap);
            tommieCaresCase.Probation_Advisor_Contact__c = getAdvisorInfo('Id', 'Probationary Advisor', advisorContactsMap);
            tommieCaresCase.Financial_Aid_Counselor_Email__c = getAdvisorInfo('Email', 'Financial Aid Counselor', advisorContactsMap);
            tommieCaresCase.Financial_Aid_Counselor__c = getAdvisorInfo('Id', 'Financial Aid Counselor', advisorContactsMap);
            tommieCaresCase.General_Advisor_Email__c = getAdvisorInfo('Email', 'General Advisor', advisorContactsMap);
            tommieCaresCase.General_Advisor__c = getAdvisorInfo('Id', 'General Advisor', advisorContactsMap);
            tommieCaresCase.International_Advisor_Email__c = getAdvisorInfo('Email', 'International Advisor', advisorContactsMap);
            tommieCaresCase.International_Advisor__c = getAdvisorInfo('Id', 'International Advisor', advisorContactsMap);
            tommieCaresCase.Faculty_Advisor_Email__c = getAdvisorInfo('Email', 'Faculty Advisor', advisorContactsMap);
            tommieCaresCase.Faculty_Advisor__c = getAdvisorInfo('Id', 'Faculty Advisor', advisorContactsMap);
        }

        System.debug('tommieCaresCase: ' + JSON.serializePretty(tommieCaresCase));

        List<hed__Course_Enrollment__c> courseConnection = [
                SELECT Id
                FROM hed__Course_Enrollment__c
                WHERE hed__Contact__r.Id = :tommieCaresCase.ContactId
                AND hed__Course_Offering__c = :studentCourseConnection
        ];

        if (courseConnection.size() > 0) {
            tommieCaresCase.Course_Connection__c = courseConnection[0].Id;
        }

        System.debug(JSON.serializePretty(tommieCaresCase));
        crud2Do.insertCase(tommieCaresCase);
        return savePage;
    }

    public String getAdvisorInfo(String EmailOrId, String relationshipType, Map<String, hed__Relationship__c> advisorContactsMap) {
        String advisorInfo = '';
        if (advisorContactsMap.size() > 0) {
            if (advisorContactsMap.containsKey(relationshipType)) {
                if (EmailOrId == 'Id') {
                    advisorInfo = advisorContactsMap.get(relationshipType).hed__Contact__r.Id;
                } else if (EmailOrId == 'Email') {
                    advisorInfo = advisorContactsMap.get(relationshipType).hed__Contact__r.Email;
                }
            }
        }
        return advisorInfo;
    }


    public List<SelectOption> getPicklists(Schema.DescribeFieldResult atObj, Boolean showSelectLabel) {
        List<SelectOption> listOut = new List<SelectOption>();
        List<Schema.PicklistEntry> ple = atObj.getPicklistValues();
        if (showSelectLabel) {
            listOut.add(new SelectOption('', 'Select...'));
        }
        for (Integer ii = 0; ii < ple.size(); ii++) {
            listOut.add(new SelectOption(ple[ii].getLabel(), ple[ii].getValue()));
        }
        return listOut;
    }

    public without sharing class doCrud {

        public Contact getAdvisor(String bannerId) {
            Contact advisor = new Contact();
            try {
                advisor = [
                        SELECT Name, Id, Last_Name_First_Name__c, hed__UniversityEmail__c
                        FROM Contact
                        WHERE University_Banner_ID__c = :bannerId
                        LIMIT 1
                ];

            } catch (Exception e) {
                System.debug(e.getMessage());
            }
            return advisor;
        }

        public List<SelectOption> getCourses(String bannerIdAdvisor) {
            List<SelectOption> coursesList = new List<SelectOption>();

            //Get a list of current term courses assigned to that advisor
            coursesList.add(new SelectOption('', 'Select...'));

            List<hed__Course_Offering__c> advisorCourses = [
                    SELECT Id, Name, Course_Title__c, hed__Section_ID__c, hed__Faculty__r.University_Banner_ID__c
                    FROM hed__Course_Offering__c
                    WHERE hed__Faculty__r.University_Banner_ID__c = :bannerIdAdvisor
                    AND Current_Term__c = TRUE
                    ORDER BY Name ASC
            ];

            for (hed__Course_Offering__c course : advisorCourses) {
                coursesList.add(new SelectOption(course.Id, course.Name + ' - ' + course.hed__Section_ID__c + ' (' + course.Course_Title__c + ')'));
            }
            return coursesList;
        }

        public List<SelectOption> getStudents(Id courseOfferingId) {
            List<SelectOption> studentList = new List<SelectOption>() ;
            studentList.add(new SelectOption('', 'Select...'));
            Id studentRecordId = Schema.SObjectType.hed__Course_Enrollment__c.getRecordTypeInfosByName().get('Student').getRecordTypeId();
            List<hed__Course_Enrollment__c> students = [
                    SELECT hed__Contact__r.Id, hed__Contact__r.Last_Name_First_Name__c, hed__Contact__r.Advisor__r.Email, Credit_Hours__c, Id
                    FROM hed__Course_Enrollment__c
                    WHERE Current_Term_Course__c = TRUE
                    AND hed__Course_Offering__c = :courseOfferingId
                    AND RecordTypeId = :studentRecordId
                    AND Course_Connection_Deleted_in_Banner__c = FALSE
                    AND (Registration_Code__c = 'OR'
                    OR Registration_Code__c = 'RE')
//                    AND Credit_Hours__c != NULL
//                    AND Credit_Hours__c != '0'
                    ORDER BY hed__Contact__r.Last_Name_First_Name__c ASC
            ];

            Map<Id, String> uniqueStudents = new Map<Id, String>();
            for (hed__Course_Enrollment__c student : students) {
                uniqueStudents.put(student.hed__Contact__r.Id, student.hed__Contact__r.Last_Name_First_Name__c);
            }

            for (Id key : uniqueStudents.keySet()) {
                studentList.add(new SelectOption(key, uniqueStudents.get(key)));
            }
            return studentList;
        }

        public void insertCase(Case caseToInsert) {
            try {
                insert caseToInsert;
            } catch (Exception e) {
                System.debug(e.getMessage());
            }
        }

    }
}