force-app/main/default/objects/Case/fields/Academic_Performance_Reason_s__c.field-meta.xml
<CustomField>
    <fullName>Academic_Performance_Reason_s__c</fullName>
    <label>Academic Performance Reason(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Performance on tests</fullName>
            </value>
            <value>
                <fullName>Performance on assignments or papers</fullName>
            </value>
            <value>
                <fullName>Missing assignments</fullName>
            </value>
            <value>
                <fullName>Missing tests or other major assessments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Alert_Term_lookup__c.field-meta.xml
<CustomField>
    <fullName>Alert_Term_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the term object for this alert. Use the Banner term format (example: 202040) and not the friendly name format (example Fall 2020)</description>
    <inlineHelpText>Lookup to the term object for this alert. Use the Banner term format (example: 202040) and not the friendly name format (example Fall 2020)</inlineHelpText>
    <label>Alert Term (lookup)</label>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Alert Term Cases</relationshipLabel>
    <relationshipName>Alert_Term_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Attendance_Concerns_Reason_s__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Concerns_Reason_s__c</fullName>
    <label>Attendance Concerns Reason(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Missing periodically</fullName>
            </value>
            <value>
                <fullName>Missing excessively</fullName>
            </value>
            <value>
                <fullName>Stopped attending and/or never attended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Reporter__c.field-meta.xml
<CustomField>
    <fullName>Case_Reporter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Faculty or Staff member who opened this case.</description>
    <label>Case Reporter</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Case Reporter)</relationshipLabel>
    <relationshipName>Tommie_Cares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Course_Connection__c.field-meta.xml
<CustomField>
    <fullName>Course_Connection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Connection</label>
    <referenceTo>hed__Course_Enrollment__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>Course_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Offering</label>
    <referenceTo>hed__Course_Offering__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Primary_Advisory_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Advisory_Email__c</fullName>
    <label>Primary Advisory Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Reporter_University_Email__c.field-meta.xml
<CustomField>
    <fullName>Reporter_University_Email__c</fullName>
    <label>Reporter University Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tommie_Alert_Primary_Reason__c.field-meta.xml
<CustomField>
    <fullName>Tommie_Alert_Primary_Reason__c</fullName>
    <inlineHelpText>Behavior concerns (threatening, intimidating, disrespectful, hostile, etc)
Mental health concerns (anxiety, depression, mood swings, etc)
Sense of belonging (not connecting on campus)</inlineHelpText>
    <label>Tommie Alert Reason(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tommie High 5</fullName>
            </value>
            <value>
                <fullName>Attendance concerns</fullName>
            </value>
            <value>
                <fullName>Academic performance concerns</fullName>
            </value>
            <value>
                <fullName>Behavior concerns</fullName>
            </value>
            <value>
                <fullName>Financial concerns</fullName>
            </value>
            <value>
                <fullName>Mental health concerns</fullName>
            </value>
            <value>
                <fullName>Relationship violence/stalking</fullName>
            </value>
            <value>
                <fullName>Sense of belonging</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Non-Responsive to Outreach</fullName>
            </value>
            <value>
                <fullName>Missed Advising Appointment</fullName>
            </value>
            <value>
                <fullName>Difficulty Meeting Basic Needs (food/housing, etc)</fullName>
            </value>
            <value>
                <fullName>Life Circumstances Impacting Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Tommie_High_5__c.field-meta.xml
<CustomField>
    <fullName>Tommie_High_5__c</fullName>
    <description>Keep Up the Good Work (use to recognize good work in the classroom) 
Showing Improvement (use when a student has showed improvement in a course</description>
    <inlineHelpText>Keep Up the Good Work (use to recognize good work in the classroom) 
Showing Improvement (use when a student has showed improvement in a course</inlineHelpText>
    <label>Tommie High 5 Reason(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Keep Up the Good Work</fullName>
            </value>
            <value>
                <fullName>Showing Improvement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TommieCaresController.cls
/**
 * Created by frie9974 on 8/14/2023.
 */
public with sharing class TommieCaresController {
    public String bannerId { get; set; }
    public Contact advisor { get; set; }
    public hed__Term__c currentTerm { get; set; }
    public List<SelectOption> courses { get; set; }
    public Case tommieCaresCase { get; set; }
    public Id studentCourseConnection { get; set; }
    public Id courseOfferingId { get; set; }
    public String primaryConcern { get; set; }
    public String highFiveReason { get; set; }
    public String academicConcern { get; set; }
    public String attendanceConcern { get; set; }
    public doCrud crud2Do { get; set; }
    public Boolean caseSubmitted { get; set; }

    public TommieCaresController() {
        tommieCaresCase = new Case();
        caseSubmitted = false;
        crud2Do = new doCrud();
        if (String.isNotBlank(ApexPages.currentPage().getParameters().get('bid'))) {
            bannerId = ApexPages.currentPage().getParameters().get('bid').escapeHtml4();
        }

        if (String.isNotBlank(ApexPages.currentPage().getParameters().get('submitted'))) {
            try {
                caseSubmitted = Boolean.valueOf(ApexPages.currentPage().getParameters().get('submitted').escapeHtml4());
            } catch (Exception e) {

            }
        }

        currentTerm = [
                SELECT ID
                FROM hed__Term__c
                WHERE Current_Term__c = TRUE
                LIMIT 1
        ];

        courses = new List<SelectOption>();

        if (!String.isBlank(bannerId)) {
            advisor = crud2Do.getAdvisor(bannerId);
            if (advisor != null) {
                courses = crud2Do.getCourses(bannerId);
            }
        }
    }

    public List<SelectOption> getStudentsOptions() {
        return crud2Do.getStudents(courseOfferingId);
    }

    public List<SelectOption> getPrimaryReasonOptions() {
        return getPicklists(Case.Tommie_Alert_Primary_Reason__c.getDescribe(), false);
    }

    public List<SelectOption> getAcademicConcernOptions() {
        return getPicklists(Case.Academic_Performance_Reason_s__c.getDescribe(), false);
    }

    public List<SelectOption> getAttendanceConcernsOptions() {
        return getPicklists(Case.Attendance_Concerns_Reason_s__c.getDescribe(), false);
    }

    public List<SelectOption> getTommieHigh5ReasonOptions() {
        return getPicklists(Case.Tommie_High_5__c.getDescribe(), false);
    }

    public PageReference saveCase() {
        System.debug('saving case for tommie cares');
        Id tcCaseRTID = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Tommie Cares').getRecordTypeId();

        PageReference savePage = Page.TommieCares;
        if (String.isNotBlank(bannerId)) {
            savePage.getParameters().put('bid', bannerId);
            savePage.getParameters().put('submitted', 'true');
            savePage.setRedirect(true);
        }
        System.debug(savePage);
        tommieCaresCase.RecordTypeId = tcCaseRTID;
        tommieCaresCase.Case_Reporter__c = advisor.Id;
        tommieCaresCase.Subject = 'Tommie Cares';
        tommieCaresCase.Origin = 'Web';
        tommieCaresCase.Course_Offering__c = studentCourseConnection;
        //tommieCaresCase.Course_Connection__c = ''
        tommieCaresCase.Reporter_University_Email__c = advisor.hed__UniversityEmail__c;
        tommieCaresCase.Alert_Term_lookup__c = currentTerm.Id;
        tommieCaresCase.Tommie_Alert_Primary_Reason__c = primaryConcern;
        tommieCaresCase.Tommie_High_5__c = highFiveReason;
        tommieCaresCase.Attendance_Concerns_Reason_s__c = attendanceConcern;
        //tommieCaresCase.Primary_Advisory_Email__c = advisor.hed__UniversityEmail__c;
        tommieCaresCase.Academic_Performance_Reason_s__c = academicConcern;

        System.debug(JSON.serializePretty(tommieCaresCase));
        crud2Do.insertCase(tommieCaresCase);
        return savePage;
    }

    public List<SelectOption> getPicklists(Schema.DescribeFieldResult atObj, Boolean showSelectLabel) {
        List<SelectOPtion> listOut = new List<SelectOption>();
        List<Schema.PicklistEntry> ple = atObj.getPicklistValues();
        if (showSelectLabel) {
            listOut.add(new SelectOption('', 'Select...'));
        }
        for (Integer ii = 0; ii < ple.size(); ii++) {
            listOut.add(new SelectOption(ple[ii].getLabel(), ple[ii].getValue()));
        }
        return listOut;
    }

    public without sharing class doCrud {

        public Contact getAdvisor(String bannerId) {
            Contact advisor = new Contact();
            try {
                advisor = [
                        SELECT Name, Id, Last_Name_First_Name__c, hed__UniversityEmail__c
                        FROM Contact
                        WHERE University_Banner_ID__c = :bannerId
                        LIMIT 1
                ];

            } catch (Exception e) {
                System.debug(e.getMessage());
            }
            return advisor;
        }

        public List<SelectOption> getCourses(String bannerIdAdvisor) {
            List<SelectOption> coursesList = new List<SelectOption>();

            //Get a list of current term courses assigned to that advisor
            coursesList.add(new SelectOption('', 'Select...'));

            List<hed__Course_Offering__c> advisorCourses = [
                    SELECT Id, Name
                    FROM hed__Course_Offering__c
                    WHERE hed__Faculty__r.University_Banner_ID__c = :bannerIdAdvisor
                    AND Current_Term__c = TRUE
                    ORDER BY Name ASC
            ];

            for (hed__Course_Offering__c co : advisorCourses) {
                coursesList.add(new SelectOption(co.Id, co.Name));
            }
            return coursesList;
        }

        public List<SelectOption> getStudents(Id stuc) {
            List<SelectOption> studentList = new List<SelectOption>() ;
            studentList.add(new SelectOption('', 'Select...'));
            List<hed__Course_Enrollment__c> stuList = [
                    SELECT hed__Contact__r.Id, hed__Contact__r.Last_Name_First_Name__c
                    FROM hed__Course_Enrollment__c
                    WHERE Current_Term_Course__c = TRUE
                    AND hed__Course_Offering__c = :stuc
                    AND RecordType.Name = 'Student'
                    ORDER BY hed__Contact__r.Last_Name_First_Name__c ASC
            ];

            for (hed__Course_Enrollment__c stu : stuList) {
                studentList.add(new SelectOption(stu.hed__Contact__r.Id, stu.hed__Contact__r.Last_Name_First_Name__c));
            }
            return studentList;
        }


        public void insertCase(Case caseToInsert) {
            //try {
            insert caseToInsert;
            //  } catch (Exception e) {
            //      System.debug(e.getMessage());
            //  }
        }

    }

}