force-app/main/default/objects/Case/fields/Academic_Performance_Reason_s__c.field-meta.xml
<CustomField>
    <fullName>Academic_Performance_Reason_s__c</fullName>
    <label>Academic Performance Reason(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Performance on tests</fullName>
            </value>
            <value>
                <fullName>Performance on assignments or papers</fullName>
            </value>
            <value>
                <fullName>Missing assignments</fullName>
            </value>
            <value>
                <fullName>Missing tests or other major assessments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Alert_Term_lookup__c.field-meta.xml
<CustomField>
    <fullName>Alert_Term_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the term object for this alert. Use the Banner term format (example: 202040) and not the friendly name format (example Fall 2020)</description>
    <inlineHelpText>Lookup to the term object for this alert. Use the Banner term format (example: 202040) and not the friendly name format (example Fall 2020)</inlineHelpText>
    <label>Alert Term (lookup)</label>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Alert Term Cases</relationshipLabel>
    <relationshipName>Alert_Term_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Attendance_Concerns_Reason_s__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Concerns_Reason_s__c</fullName>
    <label>Attendance Concerns Reason(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Missing periodically</fullName>
            </value>
            <value>
                <fullName>Missing excessively</fullName>
            </value>
            <value>
                <fullName>Stopped attending and/or never attended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Can_this_student_pass_course__c.field-meta.xml
<CustomField>
    <fullName>Can_this_student_pass_course__c</fullName>
    <description>Does this student have the ability to pass your course (if applicable):</description>
    <inlineHelpText>Does this student have the ability to pass your course (if applicable):</inlineHelpText>
    <label>Can this student pass course?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Maybe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Reporter__c.field-meta.xml
<CustomField>
    <fullName>Case_Reporter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Faculty or Staff member who opened this case.</description>
    <label>Case Reporter</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Case Reporter)</relationshipLabel>
    <relationshipName>Tommie_Cares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Course_Connection__c.field-meta.xml
<CustomField>
    <fullName>Course_Connection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Connection</label>
    <referenceTo>hed__Course_Enrollment__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>Course_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Offering</label>
    <referenceTo>hed__Course_Offering__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Faculty_Advisor__c.field-meta.xml
<CustomField>
    <fullName>Faculty_Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Faculty Advisor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Faculty Advisor)</relationshipLabel>
    <relationshipName>Cases8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Faculty_Advisor_Email__c.field-meta.xml
<CustomField>
    <fullName>Faculty_Advisor_Email__c</fullName>
    <label>Faculty Advisor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Financial_Aid_Counselor__c.field-meta.xml
<CustomField>
    <fullName>Financial_Aid_Counselor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Aid Counselor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Financial Aid Counselor)</relationshipLabel>
    <relationshipName>Cases4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Financial_Aid_Counselor_Email__c.field-meta.xml
<CustomField>
    <fullName>Financial_Aid_Counselor_Email__c</fullName>
    <label>Financial Aid Counselor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/First_Year_Advisor__c.field-meta.xml
<CustomField>
    <fullName>First_Year_Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>First-Year Advisor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (First-Year Advisor)</relationshipLabel>
    <relationshipName>Cases3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/First_Year_Advisor_Email__c.field-meta.xml
<CustomField>
    <fullName>First_Year_Advisor_Email__c</fullName>
    <label>First-Year Advisor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/General_Advisor__c.field-meta.xml
<CustomField>
    <fullName>General_Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>General Advisor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (General Advisor)</relationshipLabel>
    <relationshipName>Cases9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/General_Advisor_Email__c.field-meta.xml
<CustomField>
    <fullName>General_Advisor_Email__c</fullName>
    <label>General Advisor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/International_Advisor__c.field-meta.xml
<CustomField>
    <fullName>International_Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>International Advisor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (International Advisor)</relationshipLabel>
    <relationshipName>Cases6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/International_Advisor_Email__c.field-meta.xml
<CustomField>
    <fullName>International_Advisor_Email__c</fullName>
    <label>International Advisor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Primary_Advisor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Advisor_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Advisor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Primary Advisor Contact)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Primary_Advisory_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Advisory_Email__c</fullName>
    <label>Primary Advisory Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Probation_Advisor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Probation_Advisor_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Probation Advisor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Probation Advisor Contact)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Probation_Advisor_Email__c.field-meta.xml
<CustomField>
    <fullName>Probation_Advisor_Email__c</fullName>
    <label>Probation Advisor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Reporter_University_Email__c.field-meta.xml
<CustomField>
    <fullName>Reporter_University_Email__c</fullName>
    <label>Reporter University Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Student_Athlete_Advisor__c.field-meta.xml
<CustomField>
    <fullName>Student_Athlete_Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student-Athlete Advisor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Student-Athlete Advisor)</relationshipLabel>
    <relationshipName>Cases5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Student_Athlete_Advisor_Email__c.field-meta.xml
<CustomField>
    <fullName>Student_Athlete_Advisor_Email__c</fullName>
    <label>Student-Athlete Advisor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tommie_Alert_Primary_Reason__c.field-meta.xml
<CustomField>
    <fullName>Tommie_Alert_Primary_Reason__c</fullName>
    <inlineHelpText>Behavior concerns (threatening, intimidating, disrespectful, hostile, etc)
Mental health concerns (anxiety, depression, mood swings, etc)
Sense of belonging (not connecting on campus)</inlineHelpText>
    <label>Tommie Alert Reason(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tommie High 5</fullName>
            </value>
            <value>
                <fullName>Attendance concerns</fullName>
            </value>
            <value>
                <fullName>Academic performance concerns</fullName>
            </value>
            <value>
                <fullName>Behavior concerns</fullName>
            </value>
            <value>
                <fullName>Financial concerns</fullName>
            </value>
            <value>
                <fullName>Mental health concerns</fullName>
            </value>
            <value>
                <fullName>Relationship violence/stalking</fullName>
            </value>
            <value>
                <fullName>Sense of belonging</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Non-Responsive to Outreach</fullName>
            </value>
            <value>
                <fullName>Missed Advising Appointment</fullName>
            </value>
            <value>
                <fullName>Difficulty Meeting Basic Needs (food/housing, etc)</fullName>
            </value>
            <value>
                <fullName>Life Circumstances Impacting Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Tommie_Alert_Primary_Reason_Other_Notes__c.field-meta.xml
<CustomField>
    <fullName>Tommie_Alert_Primary_Reason_Other_Notes__c</fullName>
    <label>Tommie Alert Primary Reason Other Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tommie_High_5__c.field-meta.xml
<CustomField>
    <fullName>Tommie_High_5__c</fullName>
    <description>Keep Up the Good Work (use to recognize good work in the classroom) 
Showing Improvement (use when a student has showed improvement in a course</description>
    <inlineHelpText>Keep Up the Good Work (use to recognize good work in the classroom) 
Showing Improvement (use when a student has showed improvement in a course</inlineHelpText>
    <label>Tommie High 5 Reason(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Keep Up the Good Work</fullName>
            </value>
            <value>
                <fullName>Showing Improvement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Tommie_High_5_Notes__c.field-meta.xml
<CustomField>
    <fullName>Tommie_High_5_Notes__c</fullName>
    <label>Tommie High 5 Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Tommie_Cares.recordType-meta.xml
<RecordType>
    <fullName>Tommie_Cares</fullName>
    <active>true</active>
    <businessProcess>UST</businessProcess>
    <description>Formerly known as Current Student Alerts</description>
    <label>Tommie Cares</label>
</RecordType>

force-app/main/default/classes/TommieCaresLwcControllerv2.cls
/**
 * Created by nguy0092 on 10/14/2024.
 */

public without sharing class TommieCaresLwcControllerv2 {

    @AuraEnabled(Cacheable=true)
    public static Map<String, List<PicklistOption>> getTommieCaresPicklists() {
        Map<String, List<PicklistOption>> result = new Map<String, List<PicklistOption>>();

        result.put('tommieCaresReasons', getPicklistOptions(Case.Tommie_Alert_Primary_Reason__c));
        result.put('tommieHigh5Reasons', getPicklistOptions(Case.Tommie_High_5__c));
        result.put('academicPerformanceReasons', getPicklistOptions(Case.Academic_Performance_Reason_s__c));
        result.put('attendanceConcernsReasons', getPicklistOptions(Case.Attendance_Concerns_Reason_s__c));

        return result;
    }

    private static List<PicklistOption> getPicklistOptions(Schema.SObjectField fieldToken) {
        List<PicklistOption> options = new List<PicklistOption>();
        Schema.DescribeFieldResult dfr = fieldToken.getDescribe();

        for (Schema.PicklistEntry entry : dfr.getPicklistValues()) {
            if (entry.isActive()) {
                options.add(new PicklistOption(entry.getLabel(), entry.getValue()));
            }
        }
        return options;
    }

    @AuraEnabled(Cacheable=true)
    public static Map<String, String> currentTermAdvisor(String urlBid) {

        Map<String, String> termAdvisorMap = new Map<String, String>{
                'Current_Term' => '',
                'Advisor_ContactId' => '',
                'Advisor_ContactName' => '',
                'Advisor_LNameFName' => '',
                'Advisor_Email' => '',
                'Advisor_BannerId' => ''
        };
        List<hed__Term__c> currentTerm = new List<hed__Term__c>();
        List<Contact> advisor = new List<Contact>();

        currentTerm = [
                SELECT Id
                FROM hed__Term__c
                WHERE Current_Term__c = TRUE
        ];

        if (!currentTerm.isEmpty()) {
            termAdvisorMap.put('Current_Term', currentTerm[0].Id);
        }

        if (String.isNotBlank(urlBid)) {
            advisor = [
                    SELECT Id,
                            Name,
                            Last_Name_First_Name__c,
                            hed__UniversityEmail__c,
                            University_Banner_ID__c
                    FROM Contact
                    WHERE University_Banner_ID__c = :urlBid
                    WITH SECURITY_ENFORCED
            ];
        }

        if (!advisor.isEmpty()) {
            termAdvisorMap.put('Advisor_ContactId', advisor[0].Id);
            termAdvisorMap.put('Advisor_ContactName', advisor[0].Name);
            termAdvisorMap.put('Advisor_LNameFName', advisor[0].Last_Name_First_Name__c);
            termAdvisorMap.put('Advisor_Email', advisor[0].hed__UniversityEmail__c);
            termAdvisorMap.put('Advisor_BannerId', advisor[0].University_Banner_ID__c);
        }

        System.debug('termAdvisorMap: '+termAdvisorMap);
        return termAdvisorMap;
    }

    @AuraEnabled(Cacheable=true)
    public static List<Map<String, String>> advisorCoursesList(String advisorContactId, String courseCrn) {

        List<Map<String, String>> courseMapList = new List<Map<String, String>>();
        List<hed__Course_Offering__c> courses = new List<hed__Course_Offering__c>();
        String singleCrnCriteria = '';

        String allCourseCriteria = 'SELECT Id, Name, Course_Title__c, hed__Section_ID__c\n' +
                ' FROM hed__Course_Offering__c\n' +
                ' WHERE hed__Faculty__r.Id = :advisorContactId\n' +
                ' AND Current_Term__c = TRUE\n';

        String allCoursesQuery = allCourseCriteria + '\n' +
                ' ORDER BY Name ASC';

        if (String.isNotBlank(courseCrn)) {
            singleCrnCriteria = ' AND Course_CRN__c = \'' + courseCrn + '\'';

            String singleStudentQuery = allCourseCriteria + '\n' +
                    singleCrnCriteria + '\n' +
                    ' ORDER BY Name ASC';

            courses = Database.query(singleStudentQuery);
        }

        if (courses.size() == 0) {
            courses = Database.query(allCoursesQuery);
        }

        for (hed__Course_Offering__c c : courses) {

            Map<String, String> courseValueLabel = new Map<String, String>{'label' => c.Name + ' - ' + c.hed__Section_ID__c + ' (' + c.Course_Title__c + ')', 'value' => c.Id};
            courseMapList.add(courseValueLabel);
        }

        return courseMapList;
    }

    @AuraEnabled(Cacheable=true)
//    public static List<Map<String, String>> studentCourseList(String studentBannerId, String courseId) {
    public static List<hed__Course_Enrollment__c> studentCourseList(String studentBannerId, String courseId) {

//        List<Map<String, String>> studentMapList = new List<Map<String, String>>();
        List<hed__Course_Enrollment__c> students = new List<hed__Course_Enrollment__c>();
        String singleStudentCriteria = '';

        List<RecordType> recordId = [
                SELECT Id,
                        Name
                FROM RecordType
                WHERE SobjectType = 'hed__Course_Enrollment__c'
                AND DeveloperName = 'Student'
        ];

        String studentRecordId = !recordId.isEmpty() ? recordId[0].Id : '';

        String allStudentsCriteria = 'SELECT Id, hed__Contact__c, hed__Contact__r.Id,' +
                ' hed__Contact__r.FirstName, hed__Contact__r.LastName, hed__Contact__r.Mailing_First_Name__c,' +
                ' hed__Contact__r.Last_Name_First_Name__c, hed__Contact__r.hed__UniversityEmail__c,' +
                ' hed__Contact__r.University_Banner_ID__c, hed__Contact__r.St_Thomas_Connection__c\n' +
                ' FROM hed__Course_Enrollment__c\n' +
                ' WHERE Current_Term_Course__c = TRUE\n' +
                ' AND hed__Course_Offering__c = :courseId\n' +
                ' AND RecordTypeId = :studentRecordId\n' +
                ' AND Course_Connection_Deleted_in_Banner__c = FALSE\n' +
                ' AND (Registration_Code__c = \'OR\'\n' +
                ' OR Registration_Code__c = \'RE\')';

        String allStudentQuery = allStudentsCriteria + '\n' +
                ' WITH SECURITY_ENFORCED\n' +
                ' ORDER BY hed__Contact__r.Last_Name_First_Name__c ASC';

        if (String.isNotBlank(studentBannerId)) {
            singleStudentCriteria = ' AND hed__Contact__r.University_Banner_ID__c = \'' + studentBannerId + '\'';

            String singleStudentQuery = allStudentsCriteria + '\n' +
                    singleStudentCriteria + '\n' +
                    ' WITH SECURITY_ENFORCED\n' +
                    ' ORDER BY hed__Contact__r.Last_Name_First_Name__c ASC';

            students = Database.query(singleStudentQuery);
        }

        if (students.size() == 0) {
            students = Database.query(allStudentQuery);
        }

        return students;
    }

    public class advocateWellBeingWrapper {
        public String collection;
        public String caseType;
//        public Integer reporter_type;
        public String reporterName;
        public String reporterPhone;
        public String reporterEmail;
//        public Integer affiliation_of_harmed_party;
        public String students_first_name;
        public String students_email_address;
        public String students_phone_number;
        public String date_of_concerning_incident;
        public String description;
    }

    @AuraEnabled(Cacheable=false)
    public static void saveCase(Map<String, String> formSelections) {

        if (String.isNotBlank(formSelections.get('TellSomeoneWellBeingDate')) && String.isNotBlank(formSelections.get('TellSomeoneWellBeingDescription'))) {
            String wellBeingReportNumber = '';

            advocateWellBeingWrapper advocateWellBeing = new advocateWellBeingWrapper();
            advocateWellBeing.collection = '6320164b2a4a1fad79299ed27d892c07';
            advocateWellBeing.caseType = '186974515f78c9526452e03483778417';
//            advocateWellBeing.reporter_type = 2;
            advocateWellBeing.reporterName = formSelections.get('AdvisorContactName');
            advocateWellBeing.reporterPhone = '';
            advocateWellBeing.reporterEmail = formSelections.get('AdvisorEmail');
//            advocateWellBeing.affiliation_of_harmed_party = 1;
            advocateWellBeing.students_first_name = formSelections.get('StudentName');
            advocateWellBeing.students_email_address = formSelections.get('StudentEmail');
            advocateWellBeing.students_phone_number = '';
            advocateWellBeing.date_of_concerning_incident = formSelections.get('TellSomeoneWellBeingDate');
            advocateWellBeing.description = formSelections.get('TellSomeoneWellBeingDescription');

            String advocateWellBeingString = JSON.serialize(advocateWellBeing);
            System.debug('advocateWellBeingString: ' + advocateWellBeingString);

            HttpRequest req = new HttpRequest();
            req.setEndpoint('callout:Symplicity_Advocate_Flex_Forms/v1/fw/cases');
            req.setMethod('POST');
            req.setHeader('Content-Type', 'application/json;charset=UTF-8');
            req.setBody(advocateWellBeingString);

            try {
                Http http = new Http();
                HttpResponse response = http.send(req);
                System.debug('Response: ' + response.getBody());
                if (response.getStatusCode() == 200 || response.getStatusCode() == 201) {
                    Map<String, Object> responseBody = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
                    wellBeingReportNumber = (String) responseBody.get('reportNumber'); //for Well Being Cases
                }
            } catch (Exception e) {
                System.debug('Error occurred while sending request: ' + e.getMessage());
            }

            if (String.isNotBlank(wellBeingReportNumber)) {
                formSelections.put('CaseDescription', 'Advocate Record Number: ' + wellBeingReportNumber + ' | ' + formSelections.get('TellSomeoneWellBeingDescription'));
            } else {
                formSelections.put('CaseDescription', 'Advocate Record Number: Unable to create record. Reach out to Dean of Students with questions'+ ' | ' + formSelections.get('TellSomeoneWellBeingDescription'));
            }
            System.debug('formSelections CaseDescription: ' + formSelections.get('CaseDescription'));
        }

        Case tommieCaresCase = new Case();

        List<RecordType> recordId = [
                SELECT Id,
                        Name
                FROM RecordType
                WHERE SobjectType = 'Case'
                AND DeveloperName = 'Tommie_Cares'
        ];

        String caseRecordId = !recordId.isEmpty() ? recordId[0].Id : '';

        tommieCaresCase.RecordTypeId = caseRecordId;
        tommieCaresCase.Case_Reporter__c = formSelections.get('AdvisorContactId');
        tommieCaresCase.Subject = 'Tommie Cares';
        tommieCaresCase.Origin = 'Web';
        tommieCaresCase.Reporter_University_Email__c = formSelections.get('AdvisorEmail');
        tommieCaresCase.ContactId = formSelections.get('StudentContactId');
        tommieCaresCase.Course_Offering__c = formSelections.get('CourseSelectionId');
        tommieCaresCase.Alert_Term_lookup__c = formSelections.get('currentTermId');
        tommieCaresCase.Tommie_Alert_Primary_Reason__c = formSelections.get('TommieCares_Reasons');
        tommieCaresCase.Tommie_High_5__c = formSelections.get('High5_Reasons');
        tommieCaresCase.Attendance_Concerns_Reason_s__c = formSelections.get('Attendance_Reasons');
        tommieCaresCase.Academic_Performance_Reason_s__c = formSelections.get('Academic_Reasons');
        tommieCaresCase.Can_this_student_pass_course__c = formSelections.get('Pass_Course_Selection');
        tommieCaresCase.Tommie_High_5_Notes__c = formSelections.get('High5_Details');
        tommieCaresCase.Tommie_Alert_Primary_Reason_Other_Notes__c = formSelections.get('Other_Details');
        tommieCaresCase.Case_Reporter_Notes_to_Student__c = formSelections.get('Personal_Message');
        tommieCaresCase.Shared_Case_Notes__c = formSelections.get('Additional_Concerns');
        tommieCaresCase.Description = formSelections.containsKey('CaseDescription') ? formSelections.get('CaseDescription') : '';

        //Get Course Connection for student selected
        List<hed__Course_Enrollment__c> studentCourseEnrollmentList = [
                SELECT Id
                FROM hed__Course_Enrollment__c
                WHERE Course_Offering_ID__c = :tommieCaresCase.Course_Offering__c
                AND hed__Contact__c = :tommieCaresCase.ContactId
                WITH SECURITY_ENFORCED
        ];

        if (studentCourseEnrollmentList.size() > 0) {
            tommieCaresCase.Course_Connection__c = studentCourseEnrollmentList[studentCourseEnrollmentList.size() - 1].Id;
        }

        List <String> relationshipTypes = new List<String>{
                'Primary Advisor',
                'Student-Athlete Advisor',
                'Secondary Advisor',
                'First-Year Advisor',
                'Probationary Advisor',
                'Financial Aid Counselor',
                'General Advisor',
                'International Advisor',
                'Faculty Advisor'
        };

        //Get All Relationship Information
        List<hed__Relationship__c> advisorContacts = [
                SELECT hed__Contact__c,
                        hed__Contact__r.Id,
                        hed__Contact__r.Name,
                        hed__Contact__r.Email,
                        Name,
                        hed__Type__c,
                        hed__Status__c,
                        hed__RelatedContact__r.Id,
                        hed__RelatedContact__r.Name,
                        hed__RelatedContact__r.hed__UniversityEmail__c
                FROM hed__Relationship__c
                WHERE hed__Type__c IN :relationshipTypes
                AND hed__Contact__c = :tommieCaresCase.ContactId
                AND hed__Status__c = 'Current'
                WITH SECURITY_ENFORCED
                ORDER BY CreatedDate DESC NULLS LAST

        ];

        Map<String, hed__Relationship__c> advisorContactsMap = new Map<String, hed__Relationship__c>();
        for (hed__Relationship__c contact : advisorContacts) {
            advisorContactsMap.put(contact.hed__Type__c, contact);
        }

        if (advisorContactsMap.size() > 0) {
            String primaryAdvisorEmail = getAdvisorInfo('Email', 'Primary Advisor', advisorContactsMap);
            tommieCaresCase.Primary_Advisor_Contact__c = getAdvisorInfo('Id', 'Primary Advisor', advisorContactsMap);
            tommieCaresCase.Primary_Advisory_Email__c = String.isBlank(tommieCaresCase.Primary_Advisor_Contact__c) || String.isBlank(primaryAdvisorEmail) ? 'registrar@stthomas.edu' : primaryAdvisorEmail;
            tommieCaresCase.Student_Athlete_Advisor_Email__c = getAdvisorInfo('Email', 'Student-Athlete Advisor', advisorContactsMap);
            tommieCaresCase.Student_Athlete_Advisor__c = getAdvisorInfo('Id', 'Student-Athlete Advisor', advisorContactsMap);
            tommieCaresCase.Secondary_Advisor_Email__c = getAdvisorInfo('Email', 'Secondary Advisor', advisorContactsMap);
            tommieCaresCase.Secondary_Advisor__c = getAdvisorInfo('Id', 'Secondary Advisor', advisorContactsMap);
            tommieCaresCase.First_Year_Advisor_Email__c = getAdvisorInfo('Email', 'First-Year Advisor', advisorContactsMap);
            tommieCaresCase.First_Year_Advisor__c = getAdvisorInfo('Id', 'First-Year Advisor', advisorContactsMap);
            tommieCaresCase.Probation_Advisor_Email__c = getAdvisorInfo('Email', 'Probationary Advisor', advisorContactsMap);
            tommieCaresCase.Probation_Advisor_Contact__c = getAdvisorInfo('Id', 'Probationary Advisor', advisorContactsMap);
            tommieCaresCase.Financial_Aid_Counselor_Email__c = getAdvisorInfo('Email', 'Financial Aid Counselor', advisorContactsMap);
            tommieCaresCase.Financial_Aid_Counselor__c = getAdvisorInfo('Id', 'Financial Aid Counselor', advisorContactsMap);
            tommieCaresCase.General_Advisor_Email__c = getAdvisorInfo('Email', 'General Advisor', advisorContactsMap);
            tommieCaresCase.General_Advisor__c = getAdvisorInfo('Id', 'General Advisor', advisorContactsMap);
            tommieCaresCase.International_Advisor_Email__c = getAdvisorInfo('Email', 'International Advisor', advisorContactsMap);
            tommieCaresCase.International_Advisor__c = getAdvisorInfo('Id', 'International Advisor', advisorContactsMap);
            tommieCaresCase.Faculty_Advisor_Email__c = getAdvisorInfo('Email', 'Faculty Advisor', advisorContactsMap);
            tommieCaresCase.Faculty_Advisor__c = getAdvisorInfo('Id', 'Faculty Advisor', advisorContactsMap);
        } else {
            tommieCaresCase.Primary_Advisory_Email__c = 'registrar@stthomas.edu';
        }

        List<hed__Course_Enrollment__c> courseConnection = [
                SELECT Id
                FROM hed__Course_Enrollment__c
                WHERE hed__Contact__r.Id = :tommieCaresCase.ContactId
                AND hed__Course_Offering__c = :formSelections.get('CourseSelectionId')
                WITH SECURITY_ENFORCED
        ];

        if (courseConnection.size() > 0) {
            tommieCaresCase.Course_Connection__c = courseConnection[0].Id;
        }

        System.debug(JSON.serializePretty(tommieCaresCase));

        insert tommieCaresCase;

    }

    public static String getAdvisorInfo(String EmailOrId, String relationshipType, Map<String, hed__Relationship__c> advisorContactsMap) {
        String advisorInfo;
        if (advisorContactsMap.size() > 0) {
            if (advisorContactsMap.containsKey(relationshipType)) {
                if (EmailOrId == 'Id') {
                    advisorInfo = advisorContactsMap.get(relationshipType).hed__RelatedContact__r.Id;
                } else if (EmailOrId == 'Email') {
                    advisorInfo = advisorContactsMap.get(relationshipType).hed__RelatedContact__r.hed__UniversityEmail__c;
                }
            }
        }

        return advisorInfo;
    }

    public class PicklistOption {
        @AuraEnabled public String label;
        @AuraEnabled public String value;

        public PicklistOption(String label, String value) {
            this.label = label;
            this.value = value;
        }
    }

}