force-app/main/default/objects/Case/fields/Academic_Performance_Reason_s__c.field-meta.xml
<CustomField>
    <fullName>Academic_Performance_Reason_s__c</fullName>
    <label>Academic Performance Reason(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Performance on tests</fullName>
            </value>
            <value>
                <fullName>Performance on assignments or papers</fullName>
            </value>
            <value>
                <fullName>Missing assignments</fullName>
            </value>
            <value>
                <fullName>Missing tests or other major assessments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Attendance_Concerns_Reason_s__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Concerns_Reason_s__c</fullName>
    <label>Attendance Concerns Reason(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Missing periodically</fullName>
            </value>
            <value>
                <fullName>Missing excessively</fullName>
            </value>
            <value>
                <fullName>Stopped attending and/or never attended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Can_this_student_pass_course__c.field-meta.xml
<CustomField>
    <fullName>Can_this_student_pass_course__c</fullName>
    <description>Does this student have the ability to pass your course (if applicable):</description>
    <inlineHelpText>Does this student have the ability to pass your course (if applicable):</inlineHelpText>
    <label>Can this student pass course?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Maybe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Reporter__c.field-meta.xml
<CustomField>
    <fullName>Case_Reporter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Faculty or Staff member who opened this case.</description>
    <label>Case Reporter</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Case Reporter)</relationshipLabel>
    <relationshipName>Tommie_Cares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Faculty_Advisor__c.field-meta.xml
<CustomField>
    <fullName>Faculty_Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Faculty Advisor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Faculty Advisor)</relationshipLabel>
    <relationshipName>Cases8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Faculty_Advisor_Email__c.field-meta.xml
<CustomField>
    <fullName>Faculty_Advisor_Email__c</fullName>
    <label>Faculty Advisor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Financial_Aid_Counselor__c.field-meta.xml
<CustomField>
    <fullName>Financial_Aid_Counselor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Aid Counselor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Financial Aid Counselor)</relationshipLabel>
    <relationshipName>Cases4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Financial_Aid_Counselor_Email__c.field-meta.xml
<CustomField>
    <fullName>Financial_Aid_Counselor_Email__c</fullName>
    <label>Financial Aid Counselor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/First_Year_Advisor__c.field-meta.xml
<CustomField>
    <fullName>First_Year_Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>First-Year Advisor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (First-Year Advisor)</relationshipLabel>
    <relationshipName>Cases3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/First_Year_Advisor_Email__c.field-meta.xml
<CustomField>
    <fullName>First_Year_Advisor_Email__c</fullName>
    <label>First-Year Advisor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/General_Advisor__c.field-meta.xml
<CustomField>
    <fullName>General_Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>General Advisor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (General Advisor)</relationshipLabel>
    <relationshipName>Cases9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/General_Advisor_Email__c.field-meta.xml
<CustomField>
    <fullName>General_Advisor_Email__c</fullName>
    <label>General Advisor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/International_Advisor__c.field-meta.xml
<CustomField>
    <fullName>International_Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>International Advisor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (International Advisor)</relationshipLabel>
    <relationshipName>Cases6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/International_Advisor_Email__c.field-meta.xml
<CustomField>
    <fullName>International_Advisor_Email__c</fullName>
    <label>International Advisor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Primary_Advisor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Advisor_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Advisor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Primary Advisor Contact)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Primary_Advisory_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Advisory_Email__c</fullName>
    <label>Primary Advisory Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Probation_Advisor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Probation_Advisor_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Probation Advisor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Probation Advisor Contact)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Probation_Advisor_Email__c.field-meta.xml
<CustomField>
    <fullName>Probation_Advisor_Email__c</fullName>
    <label>Probation Advisor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Reporter_University_Email__c.field-meta.xml
<CustomField>
    <fullName>Reporter_University_Email__c</fullName>
    <label>Reporter University Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Student_Athlete_Advisor__c.field-meta.xml
<CustomField>
    <fullName>Student_Athlete_Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student-Athlete Advisor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Student-Athlete Advisor)</relationshipLabel>
    <relationshipName>Cases5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Student_Athlete_Advisor_Email__c.field-meta.xml
<CustomField>
    <fullName>Student_Athlete_Advisor_Email__c</fullName>
    <label>Student-Athlete Advisor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tommie_Alert_Primary_Reason__c.field-meta.xml
<CustomField>
    <fullName>Tommie_Alert_Primary_Reason__c</fullName>
    <inlineHelpText>Behavior concerns (threatening, intimidating, disrespectful, hostile, etc)
Mental health concerns (anxiety, depression, mood swings, etc)
Sense of belonging (not connecting on campus)</inlineHelpText>
    <label>Tommie Alert Reason(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tommie High 5</fullName>
            </value>
            <value>
                <fullName>Attendance concerns</fullName>
            </value>
            <value>
                <fullName>Academic performance concerns</fullName>
            </value>
            <value>
                <fullName>Behavior concerns</fullName>
            </value>
            <value>
                <fullName>Financial concerns</fullName>
            </value>
            <value>
                <fullName>Mental health concerns</fullName>
            </value>
            <value>
                <fullName>Relationship violence/stalking</fullName>
            </value>
            <value>
                <fullName>Sense of belonging</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Non-Responsive to Outreach</fullName>
            </value>
            <value>
                <fullName>Missed Advising Appointment</fullName>
            </value>
            <value>
                <fullName>Difficulty Meeting Basic Needs (food/housing, etc)</fullName>
            </value>
            <value>
                <fullName>Life Circumstances Impacting Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Tommie_Alert_Primary_Reason_Other_Notes__c.field-meta.xml
<CustomField>
    <fullName>Tommie_Alert_Primary_Reason_Other_Notes__c</fullName>
    <label>Tommie Alert Primary Reason Other Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tommie_High_5__c.field-meta.xml
<CustomField>
    <fullName>Tommie_High_5__c</fullName>
    <description>Keep Up the Good Work (use to recognize good work in the classroom) 
Showing Improvement (use when a student has showed improvement in a course</description>
    <inlineHelpText>Keep Up the Good Work (use to recognize good work in the classroom) 
Showing Improvement (use when a student has showed improvement in a course</inlineHelpText>
    <label>Tommie High 5 Reason(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Keep Up the Good Work</fullName>
            </value>
            <value>
                <fullName>Showing Improvement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Tommie_High_5_Notes__c.field-meta.xml
<CustomField>
    <fullName>Tommie_High_5_Notes__c</fullName>
    <label>Tommie High 5 Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Tommie_Cares.recordType-meta.xml
<RecordType>
    <fullName>Tommie_Cares</fullName>
    <active>true</active>
    <businessProcess>UST</businessProcess>
    <description>Formerly known as Current Student Alerts</description>
    <label>Tommie Cares</label>
</RecordType>

force-app/main/default/classes/TommieCaresNonFacultyLwcController.cls
/**
 * Created by nguy0092 on 2/7/2025.
 */

public without sharing class TommieCaresNonFacultyLwcController {

    @AuraEnabled(Cacheable=true)
    public static Contact advisorInformation(String advisorBannerId) {

        Contact advisorContact = new Contact();
        List<Contact> advisorContactList = new List<Contact>();

        if (String.isNotBlank(advisorBannerId)) {
            advisorContactList = [
                    SELECT Id,
                            Name,
                            Email,
                            Last_Name_First_Name__c,
                            hed__UniversityEmail__c,
                            University_Banner_ID__c,
                            St_Thomas_Connection__c
                    FROM Contact
                    WHERE University_Banner_ID__c = :advisorBannerId
                    AND St_Thomas_Connection__c INCLUDES ('Faculty', 'Staff')
                    WITH SECURITY_ENFORCED
            ];
        }

        if (advisorContactList.size() > 0) {
            advisorContact = advisorContactList[0];
        }

        return advisorContact;
    }

    @AuraEnabled(Cacheable=false)
    public static void saveCase(Map<String, String> formSelections) {
        Case tommieCaresCase = new Case();

        List<RecordType> recordId = [
                SELECT Id,
                        Name
                FROM RecordType
                WHERE SobjectType = 'Case'
                AND DeveloperName = 'Tommie_Cares'
        ];

        String caseRecordId = !recordId.isEmpty() ? recordId[0].Id : '';

        tommieCaresCase.RecordTypeId = caseRecordId;
        tommieCaresCase.Case_Reporter__c = formSelections.get('AdvisorContactId');
        tommieCaresCase.Subject = 'Tommie Cares';
        tommieCaresCase.Origin = 'Web';
        tommieCaresCase.Reporter_University_Email__c = formSelections.get('AdvisorEmail');
        tommieCaresCase.ContactId = formSelections.get('StudentContactId');
        tommieCaresCase.Tommie_Alert_Primary_Reason__c = formSelections.get('TommieCares_Reasons');
        tommieCaresCase.Tommie_High_5__c = formSelections.get('High5_Reasons');
        tommieCaresCase.Attendance_Concerns_Reason_s__c = formSelections.get('Attendance_Reasons');
        tommieCaresCase.Academic_Performance_Reason_s__c = formSelections.get('Academic_Reasons');
        tommieCaresCase.Can_this_student_pass_course__c = formSelections.get('Pass_Course_Selection');
        tommieCaresCase.Tommie_High_5_Notes__c = formSelections.get('High5_Details');
        tommieCaresCase.Tommie_Alert_Primary_Reason_Other_Notes__c = formSelections.get('Other_Details');
        tommieCaresCase.Case_Reporter_Notes_to_Student__c = formSelections.get('Personal_Message');
        tommieCaresCase.Shared_Case_Notes__c = formSelections.get('Additional_Concerns');

        List <String> relationshipTypes = new List<String>{
                'Primary Advisor',
                'Student-Athlete Advisor',
                'Secondary Advisor',
                'First-Year Advisor',
                'Probationary Advisor',
                'Financial Aid Counselor',
                'General Advisor',
                'International Advisor',
                'Faculty Advisor'
        };

        //Get All Relationship Information
        List<hed__Relationship__c> advisorContacts = [
                SELECT hed__Contact__c,
                        hed__Contact__r.Id,
                        hed__Contact__r.Name,
                        hed__Contact__r.Email,
                        Name, hed__Type__c,
                        hed__Status__c,
                        hed__RelatedContact__r.Id,
                        hed__RelatedContact__r.Name,
                        hed__RelatedContact__r.hed__UniversityEmail__c
//                        hed__RelatedContact__r.Email
                FROM hed__Relationship__c
                WHERE hed__Type__c IN :relationshipTypes
                AND hed__Contact__c = :tommieCaresCase.ContactId
                AND hed__Status__c = 'Current'
                WITH SECURITY_ENFORCED
                ORDER BY CreatedDate DESC NULLS LAST
        ];

        Map<String, hed__Relationship__c> advisorContactsMap = new Map<String, hed__Relationship__c>();
        for (hed__Relationship__c contact : advisorContacts) {
            advisorContactsMap.put(contact.hed__Type__c, contact);
        }

        if (advisorContactsMap.size() > 0) {
            String primaryAdvisorEmail = getAdvisorInfo('Email', 'Primary Advisor', advisorContactsMap);
            tommieCaresCase.Primary_Advisor_Contact__c = getAdvisorInfo('Id', 'Primary Advisor', advisorContactsMap);
            tommieCaresCase.Primary_Advisory_Email__c = String.isBlank(tommieCaresCase.Primary_Advisor_Contact__c) || String.isBlank(primaryAdvisorEmail) ? 'registrar@stthomas.edu' : primaryAdvisorEmail;
            tommieCaresCase.Student_Athlete_Advisor_Email__c = getAdvisorInfo('Email', 'Student-Athlete Advisor', advisorContactsMap);
            tommieCaresCase.Student_Athlete_Advisor__c = getAdvisorInfo('Id', 'Student-Athlete Advisor', advisorContactsMap);
            tommieCaresCase.Secondary_Advisor_Email__c = getAdvisorInfo('Email', 'Secondary Advisor', advisorContactsMap);
            tommieCaresCase.Secondary_Advisor__c = getAdvisorInfo('Id', 'Secondary Advisor', advisorContactsMap);
            tommieCaresCase.First_Year_Advisor_Email__c = getAdvisorInfo('Email', 'First-Year Advisor', advisorContactsMap);
            tommieCaresCase.First_Year_Advisor__c = getAdvisorInfo('Id', 'First-Year Advisor', advisorContactsMap);
            tommieCaresCase.Probation_Advisor_Email__c = getAdvisorInfo('Email', 'Probationary Advisor', advisorContactsMap);
            tommieCaresCase.Probation_Advisor_Contact__c = getAdvisorInfo('Id', 'Probationary Advisor', advisorContactsMap);
            tommieCaresCase.Financial_Aid_Counselor_Email__c = getAdvisorInfo('Email', 'Financial Aid Counselor', advisorContactsMap);
            tommieCaresCase.Financial_Aid_Counselor__c = getAdvisorInfo('Id', 'Financial Aid Counselor', advisorContactsMap);
            tommieCaresCase.General_Advisor_Email__c = getAdvisorInfo('Email', 'General Advisor', advisorContactsMap);
            tommieCaresCase.General_Advisor__c = getAdvisorInfo('Id', 'General Advisor', advisorContactsMap);
            tommieCaresCase.International_Advisor_Email__c = getAdvisorInfo('Email', 'International Advisor', advisorContactsMap);
            tommieCaresCase.International_Advisor__c = getAdvisorInfo('Id', 'International Advisor', advisorContactsMap);
            tommieCaresCase.Faculty_Advisor_Email__c = getAdvisorInfo('Email', 'Faculty Advisor', advisorContactsMap);
            tommieCaresCase.Faculty_Advisor__c = getAdvisorInfo('Id', 'Faculty Advisor', advisorContactsMap);
        } else {
            tommieCaresCase.Primary_Advisory_Email__c = 'registrar@stthomas.edu';
        }

        System.debug(JSON.serializePretty(tommieCaresCase));

        insert tommieCaresCase;

    }

    public static String getAdvisorInfo(String EmailOrId, String relationshipType, Map<String, hed__Relationship__c> advisorContactsMap) {
        String advisorInfo;
        if (advisorContactsMap.size() > 0) {
            if (advisorContactsMap.containsKey(relationshipType)) {
                if (EmailOrId == 'Id') {
                    advisorInfo = advisorContactsMap.get(relationshipType).hed__RelatedContact__r.Id;
                } else if (EmailOrId == 'Email') {
                    advisorInfo = advisorContactsMap.get(relationshipType).hed__RelatedContact__r.hed__UniversityEmail__c;
//                    advisorInfo = advisorContactsMap.get(relationshipType).hed__RelatedContact__r.Email;
                }
            }
        }

        return advisorInfo;
    }

}